#!/bin/bash
# provision_vm.sh — one-time: create a 500 GB SSD boot disk + GPU VM with cloud-init.
#
# Idempotent: if the disk or VM already exists by name, it skips creation and
# uses the existing IDs (so re-running this is safe).
#
# Outputs:
#   - VM ID + public IP
#   - .vm_state.env (sourced by the other helpers: vm_start.sh, sync_to_vm.sh, ssh_vm.sh)
#
# Prereqs:
#   - .env populated (cp .env.example .env, then fill in)
#   - SSH public key at $SSH_PUBKEY_PATH (default ~/.ssh/id_ed25519.pub)

set -euo pipefail

cd "$(dirname "$0")"
[ -f .env ] || { echo "Missing .env (copy from .env.example)"; exit 1; }
set -a; source .env; set +a

: "${PARENT_ID:?}"
: "${SUBNET_ID:?}"
: "${VM_NAME:?}"
: "${DISK_NAME:?}"
: "${PLATFORM:?}"
: "${PRESET:?}"
: "${DISK_SIZE_GIB:?}"
: "${IMAGE_FAMILY:?}"
: "${SSH_PUBKEY_PATH:?}"

[ -f "$SSH_PUBKEY_PATH" ] || { echo "SSH pubkey not found at $SSH_PUBKEY_PATH (run: ssh-keygen -t ed25519)"; exit 1; }
SSH_PUBKEY="$(cat "$SSH_PUBKEY_PATH")"

echo "== TextWorld VR — provision VM"
echo "   project   : $PARENT_ID"
echo "   region    : ${NEBIUS_REGION:-us-central1}"
echo "   platform  : $PLATFORM ($PRESET)"
echo "   image     : $IMAGE_FAMILY"
echo "   disk      : $DISK_NAME (${DISK_SIZE_GIB} GiB)"
echo "   vm        : $VM_NAME"

# ---------------------------------------------------------------------------
# 1. Boot disk (idempotent by name).
# ---------------------------------------------------------------------------

DISK_ID=$( (nebius compute disk get-by-name --name "$DISK_NAME" --parent-id "$PARENT_ID" --format json 2>/dev/null \
    || echo '{}') | jq -r '.metadata.id // empty')

if [ -z "$DISK_ID" ]; then
    echo "-- creating disk --"
    DISK_ID=$(nebius compute disk create \
        --parent-id "$PARENT_ID" \
        --name "$DISK_NAME" \
        --size-gibibytes "$DISK_SIZE_GIB" \
        --type NETWORK_SSD \
        --source-image-family-image-family "$IMAGE_FAMILY" \
        --source-image-family-parent-id "${IMAGE_PARENT_ID:-project-u00public-images}" \
        --format json | jq -r '.resource_id // .metadata.id')
    echo "   disk: $DISK_ID"
else
    echo "-- reusing existing disk: $DISK_ID --"
fi

# ---------------------------------------------------------------------------
# 2. Cloud-init (substitute SSH pubkey).
# ---------------------------------------------------------------------------

CLOUD_INIT=$(awk -v key="$SSH_PUBKEY" '{ gsub(/__SSH_PUBKEY__/, key); print }' cloud-init.yaml)

# ---------------------------------------------------------------------------
# 3. VM (idempotent by name).
# ---------------------------------------------------------------------------

VM_ID=$( (nebius compute instance get-by-name --name "$VM_NAME" --parent-id "$PARENT_ID" --format json 2>/dev/null \
    || echo '{}') | jq -r '.metadata.id // empty')

if [ -z "$VM_ID" ]; then
    echo "-- creating VM --"
    NIC_JSON=$(jq -nc --arg sid "$SUBNET_ID" \
        '[{name:"eth0", subnet_id:$sid, ip_address:{}, public_ip_address:{}}]')

    VM_ID=$(nebius compute instance create \
        --parent-id "$PARENT_ID" \
        --name "$VM_NAME" \
        --resources-platform "$PLATFORM" \
        --resources-preset "$PRESET" \
        --boot-disk-existing-disk-id "$DISK_ID" \
        --boot-disk-attach-mode read_write \
        --network-interfaces "$NIC_JSON" \
        --cloud-init-user-data "$CLOUD_INIT" \
        --format json | jq -r '.resource_id // .metadata.id')
    echo "   vm: $VM_ID"
else
    echo "-- reusing existing VM: $VM_ID --"
fi

# ---------------------------------------------------------------------------
# 4. Wait for public IP, then write .vm_state.env.
# ---------------------------------------------------------------------------

echo "-- waiting for public IP --"
for i in $(seq 1 60); do
    PUBLIC_IP=$(nebius compute instance get --id "$VM_ID" --format json 2>/dev/null \
        | jq -r '.status.network_interfaces[0].public_ip_address.address // empty' \
        | sed 's@/.*@@')
    if [ -n "$PUBLIC_IP" ] && [ "$PUBLIC_IP" != "null" ]; then
        echo "   ip: $PUBLIC_IP"
        break
    fi
    sleep 5
done
[ -n "$PUBLIC_IP" ] || { echo "Timed out waiting for public IP"; exit 1; }

cat > .vm_state.env <<EOF
# Auto-generated by provision_vm.sh. Source this in the helper scripts.
VM_ID="$VM_ID"
DISK_ID="$DISK_ID"
PUBLIC_IP="$PUBLIC_IP"
EOF
echo "   wrote .vm_state.env"

echo
echo "== done"
echo "   ssh -i $SSH_KEY_PATH ubuntu@$PUBLIC_IP"
echo "   (cloud-init is still running; first boot takes ~3-5 min for docker + nvidia-toolkit install)"
echo "   Wait for the file /var/lib/cloud/textworld-vr-ready to exist before running setup."
echo
echo "   Next:  ./sync_to_vm.sh && ssh ... 'cd /mnt/src/textworld-vr/deploy/nebius/on_vm && ./build_and_run.sh'"
