#!/bin/bash
# bootstrap_node.sh — configure env on each compute node.
#
# Assumes BeeOND at /scratch/local/$SLURM_JOB_ID (passed via TW_STRIPED env var
# by the sbatch wrapper). Falls back to per-node /tmp if BeeOND not available
# (e.g., manual interactive ssh into a node outside a BeeOND job).
#
# Idempotent: safe to re-run.

set -uo pipefail

SCRATCH_ROOT="$HOME/scratch/phase4/textworld-vr"
SHARED_VENV="$SCRATCH_ROOT/shared/venv"

# Decide TW_TMP: prefer shared BeeOND, fall back to node-local /tmp
if [ -n "${TW_STRIPED:-}" ] && [ -d "$TW_STRIPED" ]; then
    TW_TMP="$TW_STRIPED/workdir"
    TW_HF_CACHE="$TW_STRIPED/hf_cache"
    echo "== bootstrap on $(hostname): using BeeOND at $TW_STRIPED"
else
    TW_TMP="/tmp/$USER/textworld-vr"
    TW_HF_CACHE="$TW_TMP/hf_cache"
    mkdir -p "$TW_TMP"/{code,outputs,hf_cache,run_cache}
    echo "== bootstrap on $(hostname): no BeeOND, using per-node /tmp=$TW_TMP"
fi

mkdir -p "$TW_HF_CACHE"

# Write env file
ENV_FILE="$TW_TMP/env.sh"
cat > "$ENV_FILE" <<EOF
# textworld-vr env, generated by bootstrap_node.sh at $(date -Is) on $(hostname)
export TW_SCRATCH="$SCRATCH_ROOT"
export TW_TMP="$TW_TMP"
export TW_CODE="$TW_TMP/code"
export TW_STRIPED="${TW_STRIPED:-}"

# HuggingFace cache — shared across nodes when on BeeOND
export HF_HOME="$TW_HF_CACHE"
export HUGGINGFACE_HUB_CACHE="$TW_HF_CACHE/hub"
export TRANSFORMERS_CACHE="$TW_HF_CACHE/transformers"

# Venv (lives on ~/scratch so it's visible from all nodes)
if [ -d "$SHARED_VENV/bin" ]; then
    export VIRTUAL_ENV="$SHARED_VENV"
    export PATH="\$VIRTUAL_ENV/bin:\$PATH"
fi

# PYTHONPATH so stage*_* modules resolve when running from any cwd
export PYTHONPATH="\$TW_CODE:\${PYTHONPATH:-}"

# Avoid OOM on large H100 matmul kernels
export PYTORCH_CUDA_ALLOC_CONF="expandable_segments:True"

# Convenience
alias tw-cd='cd \$TW_CODE'
EOF

echo "== wrote env: $ENV_FILE"
echo "== activate with: source $ENV_FILE"
echo
echo "== TW_TMP contents =="
ls -la "$TW_TMP" 2>/dev/null | head -10
