#!/bin/bash
# bootstrap_node.sh — run once per session on each node.
# Idempotent: safe to re-run.
#
# Creates /tmp/$USER/textworld-vr/ with code mirror, hf_cache, outputs dir,
# symlinks to the shared venv, and sets env vars.

set -euo pipefail

SCRATCH_ROOT="$HOME/scratch/phase4/textworld-vr"
TMP_ROOT="/tmp/$USER/textworld-vr"
SHARED_VENV="$SCRATCH_ROOT/shared/venv"

mkdir -p "$TMP_ROOT"/{code,outputs,hf_cache,run_cache}
mkdir -p "$TMP_ROOT/outputs"/{panoramas,pointclouds,multiview,splats,eval,logs}

echo "== bootstrap on $(hostname)"
echo "== TMP_ROOT=$TMP_ROOT"

# Rsync code: ~/scratch → /tmp. Fast, small. Excludes outputs/ (they live
# separately to avoid clobbering the durable copy).
rsync -a --delete \
    --exclude='outputs/' \
    --exclude='__pycache__/' \
    --exclude='.git/' \
    --exclude='stage3_3dgs/OpenSplat/build/' \
    "$SCRATCH_ROOT/code/" "$TMP_ROOT/code/"

# Symlink /tmp/.../outputs to scratch outputs so writes are durable by default.
# Individual scripts that want fast scratch can override via --output-dir=/tmp/...
if [ ! -L "$TMP_ROOT/code/outputs" ]; then
    ln -sfn "$SCRATCH_ROOT/outputs" "$TMP_ROOT/code/outputs"
fi

# Symlink shared venv into /tmp so code can invoke it with a stable path
if [ -d "$SHARED_VENV" ]; then
    ln -sfn "$SHARED_VENV" "$TMP_ROOT/venv"
fi

# Env file that downstream scripts source
ENV_FILE="$TMP_ROOT/env.sh"
cat > "$ENV_FILE" <<EOF
# textworld-vr env, generated by bootstrap_node.sh
export TW_SCRATCH="$SCRATCH_ROOT"
export TW_TMP="$TMP_ROOT"
export TW_CODE="$TMP_ROOT/code"

# HuggingFace cache: hot on /tmp, mirrored to ~/scratch/.../shared/hf_cache by sync_out.sh
export HF_HOME="$TMP_ROOT/hf_cache"
export HUGGINGFACE_HUB_CACHE="$TMP_ROOT/hf_cache/hub"
export TRANSFORMERS_CACHE="$TMP_ROOT/hf_cache/transformers"

# Python
if [ -d "$TMP_ROOT/venv/bin" ]; then
    export VIRTUAL_ENV="$TMP_ROOT/venv"
    export PATH="\$VIRTUAL_ENV/bin:\$PATH"
fi

# Python path so stage*_* modules resolve
export PYTHONPATH="\$TW_CODE:\${PYTHONPATH:-}"

# Prevent OOM from large matmul kernels on H100
export PYTORCH_CUDA_ALLOC_CONF="expandable_segments:True"
EOF

echo "== wrote env file: $ENV_FILE"
echo "== /tmp usage:"
du -sh "$TMP_ROOT"/* 2>/dev/null || true
echo
echo "== to activate: source $ENV_FILE"
